import os
import uuid
import json
from datetime import datetime
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# Rate limiting
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# Groq client
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# In-memory storage for content and audit log
content_store = {}
audit_log = []


# ─── Signal 1: LLM-Based Classification ───────────────────────────────────────
def llm_signal(text):
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return ONLY a JSON object with this exact format:
{{"score": 0.0, "reasoning": "brief explanation"}}

Where score is between 0.0 and 1.0:
- 0.0 means definitely human-written
- 1.0 means definitely AI-generated

Text to analyze:
{text}

Return ONLY the JSON object, nothing else."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    return round(float(result["score"]), 3)


# ─── Signal 2: Stylometric Heuristics ─────────────────────────────────────────
def stylometric_signal(text):
    import re

    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5  # not enough data, return neutral

    # Metric 1: Sentence length variance
    lengths = [len(s.split()) for s in sentences]
    avg_len = sum(lengths) / len(lengths)
    variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
    # High variance = human, low variance = AI
    # Normalize: variance > 30 is very human, variance < 5 is very AI
    variance_score = max(0.0, min(1.0, 1 - (variance / 30)))

    # Metric 2: Type-token ratio (vocabulary diversity)
    words = text.lower().split()
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)
    # Low TTR = repetitive = AI, High TTR = diverse = human
    # Normalize: TTR < 0.4 is AI-like, TTR > 0.8 is human-like
    ttr_score = max(0.0, min(1.0, 1 - ((ttr - 0.4) / 0.4)))

    # Metric 3: Punctuation density
    punct_count = sum(1 for c in text if c in '",;:()!?—')
    punct_density = punct_count / max(len(words), 1)
    # Low punctuation density = AI, higher = human
    punct_score = max(0.0, min(1.0, 1 - (punct_density / 0.1)))

    # Average the three metrics
    combined = (variance_score + ttr_score + punct_score) / 3
    return round(combined, 3)


# ─── Confidence Scoring ────────────────────────────────────────────────────────
def compute_confidence(llm_score, stylo_score):
    # LLM gets 60% weight, stylometric gets 40%
    combined = (llm_score * 0.6) + (stylo_score * 0.4)
    return round(combined, 3)


# ─── Transparency Label ────────────────────────────────────────────────────────
def get_label(confidence):
    if confidence >= 0.70:
        return {
            "verdict": "likely_ai",
            "text": (
                "Our system found strong indicators that this content may have been AI-generated. "
                "This does not mean the work has no value, but readers should be aware it may not "
                "reflect the author's original voice. If you created this yourself, you can submit "
                "an appeal below."
            )
        }
    elif confidence >= 0.40:
        return {
            "verdict": "uncertain",
            "text": (
                "Our system was unable to determine with confidence whether this content was "
                "written by a human or generated by AI. It may reflect a mix of both, or a "
                "writing style our system hasn't seen before. Take this label as a signal to "
                "look closer, not a final verdict."
            )
        }
    else:
        return {
            "verdict": "likely_human",
            "text": (
                "Our system found strong indicators that this content was written by a human. "
                "This assessment is based on writing style and structure — it is not a guarantee, "
                "but we are reasonably confident this reflects original human authorship."
            )
        }


# ─── Audit Log ────────────────────────────────────────────────────────────────
def write_log(entry):
    audit_log.append(entry)


# ─── Routes ───────────────────────────────────────────────────────────────────
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    # Run both signals
    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)

    # Compute confidence
    confidence = compute_confidence(llm_score, stylo_score)

    # Get label
    label = get_label(confidence)

    # Store content
    content_store[content_id] = {
        "text": text,
        "creator_id": creator_id,
        "status": "classified",
        "confidence": confidence,
        "verdict": label["verdict"],
    }

    # Write to audit log
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "attribution": label["verdict"],
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
    }
    write_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": label["verdict"],
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylo_score,
        "label": label["text"],
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    if content_id not in content_store:
        return jsonify({"error": "Content ID not found"}), 404

    # Update status
    content_store[content_id]["status"] = "under_review"

    # Update audit log
    for entry in audit_log:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            break

    return jsonify({
        "message": "Your appeal has been received and is under review.",
        "content_id": content_id,
        "status": "under_review",
    })


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": audit_log})


if __name__ == "__main__":
    app.run(debug=True, port=5001)